version: "3"

env:
  PORT: 8080  # Default to 8080 to avoid macOS ControlCenter conflict on port 5000
  STATIC_DIR: web/resources/static
  # cssgen common parameters
  CSSGEN_SOURCE: web/ui/styles
  CSSGEN_OUTPUT_DIR: internal/ui
  CSSGEN_PACKAGE: ui
  CSSGEN_INCLUDE: "layers/components/**/*.css,layers/utilities.css,layers/base.css"
  CSSGEN_LINT_PATHS: "internal/features/**/*.templ,internal/features/**/*.go"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ====================
  # Code Generation (generate:*)
  # ====================
  # These tasks generate Go code from source files:
  # - generate:templ : *.templ → *_templ.go
  # - generate:sqlc  : *.sql → type-safe queries
  # - generate:css   : *.css → type-safe constants
  # ====================

  generate:templ:
    desc: Generate templ templates
    sources:
      - internal/features/**/*.templ
    generates:
      - internal/features/**/*_templ.go
    cmds:
      - templ generate

  # ====================
  # Asset Bundling (build:web:*)
  # ====================
  # These tasks bundle frontend assets for deployment
  # ====================

  build:web:assets:
    desc: Bundle all web assets (CSS + JS/TS) with esbuild
    sources:
      - web/ui/styles/**/*.css
      - web/ui/components/**/*.ts
      - web/ui/libs/**/*.ts
      - web/ui/src/**/*.ts
    generates:
      - web/resources/static/styles.css
      - web/resources/static/libs/*.js
      - web/resources/static/theme-switcher.js
    cmds:
      - go run cmd/server/build/main.go

  # ====================
  # Production Build
  # ====================

  build:
    desc: Build production binary
    deps:
      - generate:all
      - build:web:assets
    cmds:
      - go build -o bin/server cmd/server/main.go

  # ====================
  # Development Commands
  # ====================

  dev:
    desc: Start development with Procfile (all watchers in parallel)
    deps:
      - generate:all
      - build:web:assets
    cmds:
      - hivemind Procfile.dev

  dev:stop:
    desc: Stop running development processes
    cmds:
      - pkill -f "hivemind Procfile.dev" || true

  dev:restart:
    desc: Restart development processes
    cmds:
      - task: dev:stop
      - task: dev

  # ====================
  # Code Generation - Combined
  # ====================

  generate:all:
    desc: Run all code generators (sqlc, cssgen, templ)
    deps:
      - generate:sqlc
      - generate:css
      - generate:templ

  generate:sqlc:
    desc: Generate type-safe database code from SQL
    sources:
      - internal/store/queries/*.sql
      - internal/store/migrations/*.sql
    generates:
      - internal/store/queries/*.go
    cmds:
      - sqlc generate

  generate:css:
    desc: Generate type-safe CSS constants from CSS files
    sources:
      - web/ui/styles/**/*.css
    generates:
      - internal/ui/styles*.gen.go
    cmds:
      - cssgen -source ${CSSGEN_SOURCE} -output-dir ${CSSGEN_OUTPUT_DIR} -package ${CSSGEN_PACKAGE} -include "${CSSGEN_INCLUDE}"

  # ====================
  # CSS Linting
  # ====================

  css:lint:
    desc: Lint CSS usage (golangci-lint style - issues only)
    cmds:
      - cssgen -lint-only -source ${CSSGEN_SOURCE} -output-dir ${CSSGEN_OUTPUT_DIR} -package ${CSSGEN_PACKAGE} -include "${CSSGEN_INCLUDE}" -lint-paths "${CSSGEN_LINT_PATHS}"

  # ====================
  # Database Commands
  # ====================

  db:reset:
    desc: Reset database (DESTRUCTIVE)
    prompt: This will delete all data. Continue?
    cmds:
      - rm -f data/*.db data/*.db-*
      - echo "Database reset complete"

  # ====================
  # Testing & Linting
  # ====================

  test:
    desc: Run all tests (package summary, shows failures inline)
    cmds:
      - gotestsum --format pkgname-and-test-fails -- ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  lint:
    desc: Run Go linters
    cmds:
      - golangci-lint run

  check:
    desc: Run tests, lint, and CSS lint (shows all errors)
    ignore_error: true
    cmds:
      - task: test
      - task: lint
      - task: css:lint

  # ====================
  # Cleanup
  # ====================

  clean:
    desc: Clean generated files and build artifacts
    cmds:
      - rm -rf bin/
      - rm -rf tmp/
      - rm -rf web/resources/static/*
      - find . -name '*_templ.go' -delete
      - rm -f internal/ui/styles*.gen.go

  # ====================
  # Tools Installation
  # ====================

  tools:install:
    desc: Install development tools
    cmds:
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/air-verse/air@latest
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/yacobolo/cssgen/cmd/cssgen@latest
      - go install github.com/DarthSim/hivemind@latest
      - go install gotest.tools/gotestsum@latest

  tools:check:
    desc: Check if required tools are installed
    cmds:
      - |
        for tool in templ air sqlc golangci-lint cssgen hivemind gotestsum; do
          if command -v $tool &> /dev/null; then
            echo "✓ $tool installed"
          else
            echo "✗ $tool missing - run 'task tools:install'"
          fi
        done
