version: '3'

env:
  STATIC_DIR: web/resources/static

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ====================
  # Build Tasks (Production)
  # ====================

  build:templ:
    desc: Generate templ templates
    aliases: [generate:templ]
    sources:
      - internal/features/**/*.templ
    generates:
      - internal/features/**/*_templ.go
    cmds:
      - templ generate

  build:web:styles:
    desc: Bundle CSS with esbuild (resolves @import statements)
    sources:
      - web/ui/styles/**/*.css
    generates:
      - web/resources/static/styles.css
    cmds:
      - go run cmd/server/build/main.go

  build:web:bundle:
    desc: Bundle JavaScript/TypeScript with esbuild
    sources:
      - web/ui/components/**/*.ts
    generates:
      - web/resources/static/libs/*.js
    cmds:
      - go run cmd/server/build/main.go

  build:web:all:
    desc: Build all web assets (CSS + JS)
    deps:
      - build:web:styles

  build:
    desc: Build production binary
    deps:
      - generate:sqlc
      - css:gen
      - build:templ
      - build:web:all
    cmds:
      - go build -o bin/server cmd/server/main.go

  # ====================
  # Live Tasks (Development with Watchers)
  # ====================

  live:templ:
    desc: Watch and regenerate templ templates
    cmds:
      - templ generate -watch

  live:web:styles:
    desc: Watch and bundle CSS with esbuild
    cmds:
      - go run cmd/server/build/main.go -watch

  live:web:bundle:
    desc: Watch and bundle JavaScript with esbuild
    cmds:
      - go run cmd/server/build/main.go -watch

  live:server:
    desc: Run server with Air (hot reload)
    cmds:
      - air

  live:
    desc: Start all watchers (run in separate terminals or use tmux/tmuxinator)
    cmds:
      - echo "Development Mode - Run these in separate terminals:"
      - echo "  1. task live:templ"
      - echo "  2. task live:web:styles"
      - echo "  3. task live:server"
      - echo ""
      - echo "Or use task dev (simplified, Air handles watchers)"

  # ====================
  # Development Commands
  # ====================

  dev:
    desc: Start development server with live reload
    aliases: [watch]
    deps:
      - generate:sqlc
      - css:gen
      - build:templ
      - build:web:styles
    cmds:
      - air

  # ====================
  # Download External Assets
  # ====================

  # download:libs:
  #   desc: Download external JavaScript libraries
  #   sources:
  #     - cmd/server/downloader/main.go
  #   generates:
  #     - web/resources/static/datastar/datastar.js
  #   cmds:
  #     - go run cmd/server/downloader/main.go
  # Note: Commented out - project uses CDN for Datastar (see base.templ)

  # ====================
  # Code Generation
  # ====================

  generate:all:
    desc: Run all code generators
    deps:
      - generate:sqlc
      - css:gen
      - build:templ

  generate:sqlc:
    desc: Generate type-safe database code from SQL
    sources:
      - internal/store/queries/*.sql
      - internal/store/migrations/*.sql
    generates:
      - internal/store/queries/*.go
    cmds:
      - sqlc generate

  css:gen:
    desc: Generate type-safe CSS constants from CSS files
    sources:
      - web/ui/styles/**/*.css
    generates:
      - internal/ui/styles*.gen.go
    cmds:
      - cssgen -source web/ui/styles -output-dir internal/ui -package ui -include "layers/components/**/*.css,layers/utilities.css,layers/base.css"

  # ====================
  # CSS Linting
  # ====================

  css:lint:
    desc: Lint CSS usage (golangci-lint style - issues only)
    cmds:
      - cssgen -lint-only -source web/ui/styles -output-dir internal/ui -package ui -include "layers/components/**/*.css,layers/utilities.css,layers/base.css" -lint-paths "internal/features/**/*.templ,internal/features/**/*.go"

  css:lint:full:
    desc: Lint with statistics and Quick Wins (planning refactors)
    cmds:
      - cssgen -lint-only -output-format full -source web/ui/styles -output-dir internal/ui -package ui -include "layers/components/**/*.css,layers/utilities.css,layers/base.css" -lint-paths "internal/features/**/*.templ,internal/features/**/*.go"

  css:report:
    desc: Generate CSS adoption report (statistics only, no issues)
    cmds:
      - cssgen -lint-only -output-format summary -source web/ui/styles -output-dir internal/ui -package ui -include "layers/components/**/*.css,layers/utilities.css,layers/base.css" -lint-paths "internal/features/**/*.templ,internal/features/**/*.go"

  css:report:md:
    desc: Export CSS report to Markdown (for GitHub issues, wikis)
    cmds:
      - cssgen -lint-only -output-format markdown -source web/ui/styles -output-dir internal/ui -package ui -include "layers/components/**/*.css,layers/utilities.css,layers/base.css" -lint-paths "internal/features/**/*.templ,internal/features/**/*.go" > css-report.md
      - echo "Report saved to css-report.md"

  # ====================
  # Database Commands
  # ====================

  db:reset:
    desc: Reset database (DESTRUCTIVE)
    prompt: This will delete all data. Continue?
    cmds:
      - rm -f data/*.db data/*.db-*
      - echo "Database reset complete"

  # ====================
  # Testing & Linting
  # ====================

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  lint:
    desc: Run Go linters
    cmds:
      - golangci-lint run

  check:
    desc: Run tests, lint, and CSS lint
    cmds:
      - task: test
      - task: lint
      - task: css:lint

  # ====================
  # Cleanup
  # ====================

  clean:
    desc: Clean generated files and build artifacts
    cmds:
      - rm -rf bin/
      - rm -rf tmp/
      - rm -rf web/resources/static/*
      - find . -name '*_templ.go' -delete
      - rm -f internal/ui/styles*.gen.go

  # ====================
  # Tools Installation
  # ====================

  tools:install:
    desc: Install development tools
    cmds:
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/air-verse/air@latest
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/yacobolo/cssgen/cmd/cssgen@latest

  tools:check:
    desc: Check if required tools are installed
    cmds:
      - |
        for tool in templ air sqlc golangci-lint cssgen; do
          if command -v $tool &> /dev/null; then
            echo "✓ $tool installed"
          else
            echo "✗ $tool missing - run 'task tools:install'"
          fi
        done
