version: '3'

tasks:
  # ====================
  # Development Commands
  # ====================
  
  default:
    desc: Show available tasks
    cmds:
      - task --list

  dev:
    desc: Start development server with live reload
    aliases: [live, watch]
    deps:
      - generate:all
    cmds:
      - air

  # ====================
  # Code Generation
  # ====================

  generate:all:
    desc: Run all code generators
    deps:
      - generate:sqlc
      - generate:templ

  generate:sqlc:
    desc: Generate type-safe database code from SQL
    sources:
      - internal/store/queries/*.sql
      - internal/store/migrations/*.sql
    generates:
      - internal/store/queries/*.go
    cmds:
      - sqlc generate

  generate:templ:
    desc: Generate Go code from templ templates
    aliases: [build:templ]
    sources:
      - features/**/*.templ
    generates:
      - features/**/*_templ.go
    cmds:
      - templ generate

  # ====================
  # Build Commands
  # ====================

  build:all:
    desc: Build production binary
    deps:
      - generate:all
      - build:web:all
    cmds:
      - go build -o bin/server cmd/server/main.go

  build:web:all:
    desc: Build all web assets
    deps:
      - build:web:styles
      - build:web:bundle

  build:web:styles:
    desc: Bundle CSS with design tokens
    sources:
      - tokens/**/*.css
      - web/src/styles/**/*.css
    generates:
      - public/styles.css
    cmds:
      - mkdir -p public
      - |
        cat \
          tokens/index.css \
          web/src/styles/main.css \
          > public/styles.css

  build:web:bundle:
    desc: Bundle JavaScript/TypeScript with esbuild
    sources:
      - web/src/components/**/*.ts
    generates:
      - public/libs/*.js
    cmds:
      - go run cmd/server/build/main.go

  # ====================
  # Database Commands
  # ====================

  db:reset:
    desc: Reset database (DESTRUCTIVE)
    prompt: This will delete all data. Continue?
    cmds:
      - rm -f data/*.db data/*.db-*
      - echo "Database reset complete"

  # ====================
  # Testing & Linting
  # ====================

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  lint:
    desc: Run Go linters
    cmds:
      - golangci-lint run

  # ====================
  # Cleanup
  # ====================

  clean:
    desc: Clean generated files and build artifacts
    cmds:
      - rm -rf bin/
      - rm -rf tmp/
      - rm -rf public/
      - find . -name '*_templ.go' -delete

  # ====================
  # Tools Installation
  # ====================

  tools:install:
    desc: Install development tools
    cmds:
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/air-verse/air@latest
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  tools:check:
    desc: Check if required tools are installed
    cmds:
      - |
        for tool in templ air sqlc golangci-lint; do
          if command -v $tool &> /dev/null; then
            echo "✓ $tool installed"
          else
            echo "✗ $tool missing - run 'task tools:install'"
          fi
        done
