// Code generated by cssgen. DO NOT EDIT.
//
// Component: Callout
// Generated: 2026-02-04 08:17:31

package ui

// Callout component styles
//
// For the full CSS class registry, see styles.gen.go

// @layer components
//
//
// **Visual:**
// - background: `var(--ui-color-surface)` 🎨
// - border: `1px solid var(--ui-color-outline)` 🎨
// - border-radius: `var(--ui-radius-md)` 🎨
// **Layout:**
// - align-items: `flex-start`
// - display: `flex`
// - gap: `var(--ui-space-sm)` 🎨
// - padding: `var(--ui-space-md)` 🎨
const Callout = "callout"

// @layer components
//
//
// **Layout:**
// - flex: `1`
const CalloutContent = "callout-content"

// @layer components
//
//
// **Visual:**
// - background: `var(--ui-color-error-container)` 🎨
// - border-color: `var(--ui-color-error)` 🎨
const CalloutError = "callout-error"

// @layer components
//
//
// **Visual:**
// - background: `var(--ui-color-surface)` 🎨
// - border-color: `var(--ui-color-outline)` 🎨
const CalloutInfo = "callout-info"

// @layer components
//
//
// **Visual:**
// - background: `var(--ui-color-primary-container)` 🎨
// - border-color: `var(--ui-color-primary)` 🎨
const CalloutSuccess = "callout-success"

