// Code generated by cssgen. DO NOT EDIT.
//
// Component: Input
// Generated: 2026-02-04 09:05:47

package ui

// Input component styles
//
// For the full CSS class registry, see styles.gen.go

// @layer components
//
//
// **Visual:**
// - background: `var(--ui-color-surface)` 🎨
// - border: `var(--ui-border-default) solid var(--ui-color-outline-variant)` 🎨
// - border-color: `var(--ui-color-primary)` 🎨
// - border-radius: `var(--ui-radius-md)` 🎨
// - color: `var(--ui-color-surface-on)` 🎨
// **Layout:**
// - display: `block`
// - focus: `{ outline none`
// - padding: `var(--ui-space-sm) var(--ui-space-md)` 🎨
// - width: `100%`
// **Typography:**
// - font-size: `var(--ui-type-size-base)` 🎨
// - line-height: `var(--ui-leading-normal)` 🎨
// **Effects:**
// - transition: `border-color var(--ui-duration-fast) var(--ui-ease-default)` 🎨
const Input = "input"

// @layer components
//
//
// **Visual:**
// - border-width: `var(--ui-border-thick)` 🎨
const InputBordered = "input-bordered"

