// Code generated by cssgen. DO NOT EDIT.
//
// Source: web/ui/styles
// Files scanned: 7
// Classes generated: 99
// Generated: 2026-02-04 08:17:31
//
// This file provides type-safe constants for CSS classes.
// Each constant includes metadata about layer, inheritance, and styles.

package ui

// Package ui provides type-safe CSS constants.
// This package is split into multiple files for readability:
// - styles_button.gen.go
// - styles_callout.gen.go
// - styles_input.gen.go
// - styles_loading.gen.go
// - styles_todo.gen.go
//
// This file contains the AllCSSClasses registry and base/utility styles.

// AllCSSClasses is a map of all CSS classes found in the source files.
// This is used by the linter to detect invalid class references.
// Generated classes, internal classes, and utility classes are all included.
var AllCSSClasses = map[string]bool{
	"bottom-md": true,
	"btn": true,
	"btn-error": true,
	"btn-ghost": true,
	"btn-lg": true,
	"btn-primary": true,
	"btn-secondary": true,
	"btn-sm": true,
	"callout": true,
	"callout-content": true,
	"callout-error": true,
	"callout-info": true,
	"callout-success": true,
	"fixed": true,
	"flex": true,
	"flex-1": true,
	"flex-col": true,
	"flex-wrap": true,
	"font-bold": true,
	"font-medium": true,
	"font-normal": true,
	"gap-2xl": true,
	"gap-lg": true,
	"gap-md": true,
	"gap-sm": true,
	"gap-xl": true,
	"gap-xs": true,
	"h-full": true,
	"hidden": true,
	"hover-text-primary": true,
	"input": true,
	"input-bordered": true,
	"invisible": true,
	"italic": true,
	"items-center": true,
	"items-start": true,
	"justify-between": true,
	"justify-center": true,
	"justify-end": true,
	"loading": true,
	"loading-dots": true,
	"m-auto": true,
	"mb-lg": true,
	"mb-md": true,
	"min-h-screen": true,
	"ml-md": true,
	"mt-md": true,
	"p-2xl": true,
	"p-lg": true,
	"p-md": true,
	"p-sm": true,
	"p-xl": true,
	"px-md": true,
	"py-md": true,
	"right-md": true,
	"rounded-lg": true,
	"rounded-md": true,
	"rounded-sm": true,
	"space-y-xs": true,
	"text-2xl": true,
	"text-3xl": true,
	"text-4xl": true,
	"text-base": true,
	"text-center": true,
	"text-error": true,
	"text-left": true,
	"text-lg": true,
	"text-muted": true,
	"text-primary": true,
	"text-right": true,
	"text-sm": true,
	"text-xl": true,
	"text-xs": true,
	"toast": true,
	"toast-error": true,
	"toast-info": true,
	"toast-success": true,
	"todo-checkbox-label": true,
	"todo-container": true,
	"todo-content": true,
	"todo-description": true,
	"todo-footer": true,
	"todo-footer-actions": true,
	"todo-footer-count": true,
	"todo-header": true,
	"todo-help-text": true,
	"todo-input": true,
	"todo-input-controls": true,
	"todo-item": true,
	"todo-item-completed": true,
	"todo-list": true,
	"todo-list-container": true,
	"todo-task-completed": true,
	"todo-text-label": true,
	"todo-title": true,
	"todo-title-section": true,
	"uppercase": true,
	"visible": true,
	"w-full": true,
}

// @layer utilities
//
//
// **Layout:**
// - bottom: `var(--ui-space-md)` 🎨
const BottomMd = "bottom-md"

// @layer utilities
//
//
// **Layout:**
// - position: `fixed`
const Fixed = "fixed"

// @layer utilities
//
//
// **Layout:**
// - display: `flex`
const Flex = "flex"

// @layer utilities
//
//
// **Layout:**
// - flex: `1`
const Flex1 = "flex-1"

// @layer utilities
//
//
// **Layout:**
// - flex-direction: `column`
const FlexCol = "flex-col"

// @layer utilities
//
//
// **Layout:**
// - flex-wrap: `wrap`
const FlexWrap = "flex-wrap"

// @layer utilities
//
//
// **Typography:**
// - font-weight: `var(--ui-weight-bold)` 🎨
const FontBold = "font-bold"

// @layer utilities
//
//
// **Typography:**
// - font-weight: `var(--ui-weight-medium)` 🎨
const FontMedium = "font-medium"

// @layer utilities
//
//
// **Typography:**
// - font-weight: `var(--ui-weight-normal)` 🎨
const FontNormal = "font-normal"

// @layer utilities
//
//
// **Layout:**
// - gap: `var(--ui-space-2xl)` 🎨
const Gap2xl = "gap-2xl"

// @layer utilities
//
//
// **Layout:**
// - gap: `var(--ui-space-lg)` 🎨
const GapLg = "gap-lg"

// @layer utilities
//
//
// **Layout:**
// - gap: `var(--ui-space-md)` 🎨
const GapMd = "gap-md"

// @layer utilities
//
//
// **Layout:**
// - gap: `var(--ui-space-sm)` 🎨
const GapSm = "gap-sm"

// @layer utilities
//
//
// **Layout:**
// - gap: `var(--ui-space-xl)` 🎨
const GapXl = "gap-xl"

// @layer utilities
//
//
// **Layout:**
// - gap: `var(--ui-space-xs)` 🎨
const GapXs = "gap-xs"

// @layer utilities
//
//
// **Layout:**
// - height: `100%`
const HFull = "h-full"

// @layer utilities
//
//
// **Layout:**
// - display: `none`
const Hidden = "hidden"

// @layer utilities
//
//
//
// **Interactions:**
// - `:hover`: Changes color to `var(--ui-color-primary)`
const HoverTextPrimary = "hover-text-primary"

// @layer utilities
//
//
// **Layout:**
// - visibility: `hidden`
const Invisible = "invisible"

// @layer utilities
//
//
// **Typography:**
// - font-style: `italic`
const Italic = "italic"

// @layer utilities
//
//
// **Layout:**
// - align-items: `center`
const ItemsCenter = "items-center"

// @layer utilities
//
//
// **Layout:**
// - align-items: `flex-start`
const ItemsStart = "items-start"

// @layer utilities
//
//
// **Layout:**
// - justify-content: `space-between`
const JustifyBetween = "justify-between"

// @layer utilities
//
//
// **Layout:**
// - justify-content: `center`
const JustifyCenter = "justify-center"

// @layer utilities
//
//
// **Layout:**
// - justify-content: `flex-end`
const JustifyEnd = "justify-end"

// @layer utilities
//
//
// **Layout:**
// - margin: `auto`
const MAuto = "m-auto"

// @layer utilities
//
//
// **Layout:**
// - margin-bottom: `var(--ui-space-lg)` 🎨
const MbLg = "mb-lg"

// @layer utilities
//
//
// **Layout:**
// - margin-bottom: `var(--ui-space-md)` 🎨
const MbMd = "mb-md"

// @layer utilities
//
//
// **Layout:**
// - min-height: `100vh`
const MinHScreen = "min-h-screen"

// @layer utilities
//
//
// **Layout:**
// - margin-left: `var(--ui-space-md)` 🎨
const MlMd = "ml-md"

// @layer utilities
//
//
// **Layout:**
// - margin-top: `var(--ui-space-md)` 🎨
const MtMd = "mt-md"

// @layer utilities
//
//
// **Layout:**
// - padding: `var(--ui-space-2xl)` 🎨
const P2xl = "p-2xl"

// @layer utilities
//
//
// **Layout:**
// - padding: `var(--ui-space-lg)` 🎨
const PLg = "p-lg"

// @layer utilities
//
//
// **Layout:**
// - padding: `var(--ui-space-md)` 🎨
const PMd = "p-md"

// @layer utilities
//
//
// **Layout:**
// - padding: `var(--ui-space-sm)` 🎨
const PSm = "p-sm"

// @layer utilities
//
//
// **Layout:**
// - padding: `var(--ui-space-xl)` 🎨
const PXl = "p-xl"

// @layer utilities
//
//
// **Layout:**
// - padding-left: `var(--ui-space-md)` 🎨
// - padding-right: `var(--ui-space-md)` 🎨
const PxMd = "px-md"

// @layer utilities
//
//
// **Layout:**
// - padding-bottom: `var(--ui-space-md)` 🎨
// - padding-top: `var(--ui-space-md)` 🎨
const PyMd = "py-md"

// @layer utilities
//
//
// **Layout:**
// - right: `var(--ui-space-md)` 🎨
const RightMd = "right-md"

// @layer utilities
//
//
// **Visual:**
// - border-radius: `var(--ui-radius-lg)` 🎨
const RoundedLg = "rounded-lg"

// @layer utilities
//
//
// **Visual:**
// - border-radius: `var(--ui-radius-md)` 🎨
const RoundedMd = "rounded-md"

// @layer utilities
//
//
// **Visual:**
// - border-radius: `var(--ui-radius-sm)` 🎨
const RoundedSm = "rounded-sm"

// @layer utilities
//
//
// **Layout:**
// - margin-top: `var(--ui-space-xs)` 🎨
const SpaceYXs = "space-y-xs"

// @layer utilities
//
//
// **Typography:**
// - font-size: `var(--ui-type-size-2xl)` 🎨
const Text2xl = "text-2xl"

// @layer utilities
//
//
// **Typography:**
// - font-size: `var(--ui-type-size-3xl)` 🎨
const Text3xl = "text-3xl"

// @layer utilities
//
//
// **Typography:**
// - font-size: `var(--ui-type-size-4xl)` 🎨
const Text4xl = "text-4xl"

// @layer utilities
//
//
// **Typography:**
// - font-size: `var(--ui-type-size-base)` 🎨
const TextBase = "text-base"

// @layer utilities
//
//
// **Typography:**
// - text-align: `center`
const TextCenter = "text-center"

// @layer utilities
//
//
// **Visual:**
// - color: `var(--ui-color-error)` 🎨
const TextError = "text-error"

// @layer utilities
//
//
// **Typography:**
// - text-align: `left`
const TextLeft = "text-left"

// @layer utilities
//
//
// **Typography:**
// - font-size: `var(--ui-type-size-lg)` 🎨
const TextLg = "text-lg"

// @layer utilities
//
//
// **Visual:**
// - color: `var(--ui-color-on-surface-variant)` 🎨
const TextMuted = "text-muted"

// @layer utilities
//
//
// **Visual:**
// - color: `var(--ui-color-primary)` 🎨
const TextPrimary = "text-primary"

// @layer utilities
//
//
// **Typography:**
// - text-align: `right`
const TextRight = "text-right"

// @layer utilities
//
//
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const TextSm = "text-sm"

// @layer utilities
//
//
// **Typography:**
// - font-size: `var(--ui-type-size-xl)` 🎨
const TextXl = "text-xl"

// @layer utilities
//
//
// **Typography:**
// - font-size: `var(--ui-type-size-xs)` 🎨
const TextXs = "text-xs"

// @layer utilities
//
//
// **Typography:**
// - text-transform: `uppercase`
const Uppercase = "uppercase"

// @layer utilities
//
//
// **Layout:**
// - visibility: `visible`
const Visible = "visible"

// @layer utilities
//
//
// **Layout:**
// - width: `100%`
const WFull = "w-full"

