// Code generated by cssgen. DO NOT EDIT.
//
// Component: Button
// Generated: 2026-02-04 11:21:00

package ui

// Button component styles
//
// For the full CSS class registry, see styles.gen.go

// @layer components
//
//
// **Visual:**
// - border: `var(--ui-border-default) solid transparent` 🎨
// - border-radius: `var(--ui-radius-md)` 🎨
// - box-shadow: `var(--ui-focus-ring)` 🎨
// **Layout:**
// - align-items: `center`
// - cursor: `pointer`
// - display: `inline-flex`
// - focus-visible: `{ outline 2px solid var(--ui-color-primary)` 🎨
// - gap: `var(--ui-space-sm)` 🎨
// - [+5 more layout properties]
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
// - font-weight: `var(--ui-weight-medium)` 🎨
// - line-height: `var(--ui-leading-snug)` 🎨
// - white-space: `nowrap`
// **Effects:**
// - transition: `background-color var(--ui-duration-fast) var(--ui-ease-default), color var(--ui-duration-fast) var(--ui-ease-default), border-color var(--ui-duration-fast) var(--ui-ease-default), transform var(--ui-duration-fast) var(--ui-ease-default), box-shadow var(--ui-duration-fast) var(--ui-ease-default)` 🎨
const Btn = "btn"

// @layer components
//
//
// **Visual:**
// - background: `currentColor`
// - border-radius: `inherit`
// - color: `var(--ui-color-error-on)` 🎨
// - opacity: `0`
// **Layout:**
// - before: `{ content ''`
// - inset: `0`
// - pointer-events: `none`
// - position: `absolute`
// **Effects:**
// - transition: `opacity var(--ui-duration-fast)` 🎨
const BtnError = "btn-error"

// @layer components
//
//
// **Visual:**
// - background: `var(--ui-color-surface-on)` 🎨
// - border-radius: `inherit`
// - color: `var(--ui-color-surface-on)` 🎨
// - opacity: `0`
// **Layout:**
// - before: `{ content ''`
// - inset: `0`
// - pointer-events: `none`
// - position: `absolute`
// **Effects:**
// - transition: `opacity var(--ui-duration-fast)` 🎨
const BtnGhost = "btn-ghost"

// @layer components
//
//
// **Layout:**
// - padding: `var(--ui-space-md) var(--ui-space-lg)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-md)` 🎨
const BtnLg = "btn-lg"

// @layer components
//
//
// **Visual:**
// - background: `currentColor`
// - border-radius: `inherit`
// - box-shadow: `var(--ui-shadow-sm)` 🎨
// - color: `var(--ui-color-primary-on)` 🎨
// - opacity: `0`
// **Layout:**
// - before: `{ content ''`
// - inset: `0`
// - pointer-events: `none`
// - position: `absolute`
// **Effects:**
// - transition: `opacity var(--ui-duration-fast)` 🎨
const BtnPrimary = "btn-primary"

// @layer components
//
//
// **Visual:**
// - background: `currentColor`
// - border-radius: `inherit`
// - color: `var(--ui-color-secondary-on)` 🎨
// - opacity: `0`
// **Layout:**
// - before: `{ content ''`
// - inset: `0`
// - pointer-events: `none`
// - position: `absolute`
// **Effects:**
// - transition: `opacity var(--ui-duration-fast)` 🎨
const BtnSecondary = "btn-secondary"

// @layer components
//
//
// **Layout:**
// - min-height: `44px`
// - padding: `var(--ui-space-sm) var(--ui-space-md)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const BtnSm = "btn-sm"

