// Code generated by cssgen. DO NOT EDIT.
//
// Component: Button
// Generated: 2026-02-03 21:52:58

package ui

// Button component styles
//
// For the full CSS class registry, see styles.gen.go

// @layer components
//
//
// **Visual:**
// - border: `var(--ui-border-md) solid transparent` 🎨
// - border-radius: `var(--ui-radius-md)` 🎨
// **Layout:**
// - align-items: `center`
// - cursor: `not-allowed`
// - disabled: `{ opacity 0.5`
// - display: `inline-flex`
// - gap: `var(--ui-space-sm)` 🎨
// - [+3 more layout properties]
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
// - font-weight: `var(--ui-weight-medium)` 🎨
// - line-height: `1`
// - white-space: `nowrap`
// **Effects:**
// - transition: `all var(--ui-duration-fast) var(--ui-ease-default)` 🎨
const Btn = "btn"

// @layer components
//
//
// **Visual:**
// - background: `var(--ui-color-error)` 🎨
// - color: `var(--ui-color-on-error)` 🎨
// **Layout:**
// - hover: `not(disabled) { opacity 0.9`
const BtnError = "btn-error"

// @layer components
//
//
// **Visual:**
// - background: `transparent`
// - color: `var(--ui-color-on-background)` 🎨
// **Layout:**
// - hover: `not(disabled) { background var(--ui-color-surface)` 🎨
const BtnGhost = "btn-ghost"

// @layer components
//
//
// **Layout:**
// - padding: `var(--ui-space-md) var(--ui-space-lg)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-md)` 🎨
const BtnLg = "btn-lg"

// @layer components
//
//
// **Visual:**
// - background: `var(--ui-color-primary)` 🎨
// - color: `var(--ui-color-on-primary)` 🎨
// **Layout:**
// - hover: `not(disabled) { background var(--ui-color-primary-container)` 🎨
const BtnPrimary = "btn-primary"

// @layer components
//
//
// **Visual:**
// - background: `var(--ui-color-secondary)` 🎨
// - color: `var(--ui-color-on-secondary)` 🎨
// **Layout:**
// - hover: `not(disabled) { background var(--ui-color-secondary-container)` 🎨
const BtnSecondary = "btn-secondary"

// @layer components
//
//
// **Layout:**
// - padding: `var(--ui-space-xs) var(--ui-space-sm)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-xs)` 🎨
const BtnSm = "btn-sm"

