// Code generated by cssgen. DO NOT EDIT.
//
// Component: Input
// Generated: 2026-02-05 10:33:12

package ui

// Input component styles
//
// For the full CSS class registry, see styles.gen.go

// @layer components
//
//
// **Visual:**
// - background: `var(--ui-color-surface)` 🎨
// - border: `var(--ui-border-thin) solid var(--ui-color-outline-variant)` 🎨
// - border-radius: `var(--ui-radius-md)` 🎨
// - color: `var(--ui-color-surface-on)` 🎨
// **Layout:**
// - display: `block`
// - hover: `not(disabled)not(focus) { border-color var(--ui-color-outline)` 🎨
// - padding: `var(--ui-space-sm) var(--ui-space-md)` 🎨
// - width: `100%`
// **Typography:**
// - font-size: `var(--ui-type-size-base)` 🎨
// - line-height: `1.5`
// **Effects:**
// - transition: `border-color var(--ui-duration-fast) var(--ui-ease-default), box-shadow var(--ui-duration-fast) var(--ui-ease-default), background var(--ui-duration-fast) var(--ui-ease-default)` 🎨
const Input = "input"

// @layer components
//
//
// **Visual:**
// - border-width: `var(--ui-border-thick)` 🎨
const InputBordered = "input-bordered"

