// Code generated by cssgen. DO NOT EDIT.
//
// Component: Todo
// Generated: 2026-02-04 09:16:41

package ui

// Todo component styles
//
// For the full CSS class registry, see styles.gen.go

// @layer components
//
//
// **Visual:**
// - border-radius: `var(--ui-radius-md)` 🎨
// - box-shadow: `var(--ui-shadow-lg)` 🎨
// **Layout:**
// - min-width: `250px`
// - padding: `var(--ui-space-md) var(--ui-space-lg)` 🎨
// **Effects:**
// - animation: `slideIn var(--ui-duration-normal) var(--ui-ease-out)` 🎨
const Toast = "toast"

// @layer components
//
//
// **Layout:**
// - bottom: `var(--ui-space-md)` 🎨
// - display: `flex`
// - flex-direction: `column`
// - gap: `var(--ui-space-xs)` 🎨
// - position: `fixed`
// - [+2 more layout properties]
const ToastContainer = "toast-container"

// @layer components
//
//
// **Visual:**
// - background: `var(--ui-color-error)` 🎨
// - color: `var(--ui-color-error-on)` 🎨
const ToastError = "toast-error"

// @layer components
//
//
// **Visual:**
// - background: `var(--ui-color-secondary)` 🎨
// - color: `var(--ui-color-secondary-on)` 🎨
const ToastInfo = "toast-info"

// @layer components
//
//
// **Visual:**
// - background: `var(--ui-color-primary)` 🎨
// - color: `var(--ui-color-primary-on)` 🎨
const ToastSuccess = "toast-success"

// @layer components
//
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - align-items: `center`
// - cursor: `pointer`
// - display: `flex`
// **Typography:**
// - font-size: `var(--ui-type-size-2xl)` 🎨
// **Effects:**
// - transition: `color var(--ui-duration-fast) var(--ui-ease-default)` 🎨
//
// **Interactions:**
// - `:hover`: Changes color to `var(--ui-color-primary)`
const TodoCheckboxLabel = "todo-checkbox-label"

// @layer components
//
//
// **Layout:**
// - margin: `0 auto`
// - max-width: `800px`
// - padding: `var(--ui-space-md)` 🎨
const TodoContainer = "todo-container"

// @layer components
//
//
// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - gap: `var(--ui-space-md)` 🎨
// - width: `100%`
const TodoContent = "todo-content"

// @layer components
//
//
// **Visual:**
// - color: `var(--ui-color-primary)` 🎨
// **Layout:**
// - margin: `0 0 var(--ui-space-md) 0` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
// - line-height: `var(--ui-leading-relaxed)` 🎨
// - text-align: `center`
// - text-decoration: `underline`
// **Effects:**
// - transition: `color var(--ui-duration-fast) var(--ui-ease-default)` 🎨
//
// **Interactions:**
// - `:hover`: Changes color to `var(--ui-color-primary-container-on)`
const TodoDescription = "todo-description"

// @layer components
//
//
// **Visual:**
// - border-top: `var(--ui-border-thin) solid var(--ui-color-outline-variant)` 🎨
// **Layout:**
// - align-items: `flex-start`
// - display: `flex`
// - flex-direction: `column`
// - flex-wrap: `wrap`
// - gap: `var(--ui-space-sm)` 🎨
// - [+3 more layout properties]
const TodoFooter = "todo-footer"

// @layer components
//
//
// **Layout:**
// - display: `flex`
// - flex-wrap: `wrap`
// - gap: `var(--ui-space-xs)` 🎨
// - width: `100%`
const TodoFooterActions = "todo-footer-actions"

// @layer components
//
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const TodoFooterCount = "todo-footer-count"

// @layer components
//
//
// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - gap: `var(--ui-space-md)` 🎨
const TodoHeader = "todo-header"

// @layer components
//
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - display: `flex`
// - justify-content: `center`
// - margin-top: `var(--ui-space-sm)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-xs)` 🎨
// - font-style: `italic`
const TodoHelpText = "todo-help-text"

// @layer components
//
//
// **Layout:**
// - flex: `1`
// - width: `100%`
// **Typography:**
// - font-size: `var(--ui-type-size-base)` 🎨
// - font-style: `italic`
const TodoInput = "todo-input"

// @layer components
//
//
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `var(--ui-space-sm)` 🎨
const TodoInputControls = "todo-input-controls"

// @layer components
//
//
// **Visual:**
// - background: `var(--ui-color-surface)` 🎨
// - border: `var(--ui-border-thin) solid var(--ui-color-outline-variant)` 🎨
// - border-radius: `var(--ui-radius-md)` 🎨
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `var(--ui-space-sm)` 🎨
// - padding: `var(--ui-space-sm) var(--ui-space-md)` 🎨
// **Effects:**
// - transition: `background var(--ui-duration-fast) var(--ui-ease-default), border-color var(--ui-duration-fast) var(--ui-ease-default)` 🎨
//
// **Interactions:**
// - `:hover`: Changes background to `var(--ui-color-surface-container)`, border-color to `var(--ui-color-outline)`
const TodoItem = "todo-item"

// @layer components
//
//
// **Visual:**
// - opacity: `0.6`
const TodoItemCompleted = "todo-item-completed"

// @layer components
//
//
// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - gap: `var(--ui-space-xs)` 🎨
// - list-style: `none`
// - margin: `0`
// - [+1 more layout properties]
const TodoList = "todo-list"

// @layer components
//
//
// **Layout:**
// - max-height: `calc(100vh - 400px)`
// - overflow: `auto`
const TodoListContainer = "todo-list-container"

// @layer components
//
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - justify-content: `center`
// - padding: `var(--ui-space-2xl)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-base)` 🎨
const TodoLoading = "todo-loading"

// @layer components
//
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Typography:**
// - text-decoration: `line-through`
const TodoTaskCompleted = "todo-task-completed"

// @layer components
//
//
// **Visual:**
// - color: `var(--ui-color-surface-on)` 🎨
// **Layout:**
// - cursor: `pointer`
// - flex: `1`
// - padding: `var(--ui-space-xs) 0` 🎨
// - user-select: `none`
// **Typography:**
// - font-size: `var(--ui-type-size-base)` 🎨
const TodoTextLabel = "todo-text-label"

// @layer components
//
//
// **Visual:**
// - color: `var(--ui-color-primary)` 🎨
// **Layout:**
// - margin: `0`
// **Typography:**
// - font-size: `var(--ui-type-size-3xl)` 🎨
// - font-weight: `var(--ui-weight-bold)` 🎨
const TodoTitle = "todo-title"

// @layer components
//
//
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `var(--ui-space-sm)` 🎨
// - justify-content: `center`
const TodoTitleSection = "todo-title-section"

