// Code generated by cssgen. DO NOT EDIT.
//
// Component: Todo
// Generated: 2026-02-04 08:17:31

package ui

// Todo component styles
//
// For the full CSS class registry, see styles.gen.go

// @layer components
//
//
// **Visual:**
// - border-radius: `var(--ui-radius-md)` 🎨
// - box-shadow: `var(--ui-shadow-lg)` 🎨
// **Layout:**
// - bottom: `var(--ui-space-lg)` 🎨
// - padding: `var(--ui-space-md) var(--ui-space-lg)` 🎨
// - position: `fixed`
// - right: `var(--ui-space-lg)` 🎨
// **Effects:**
// - animation: `slideIn 0.3s var(--ui-ease-default)` 🎨
const Toast = "toast"

// @layer components
//
//
// **Visual:**
// - background: `var(--ui-color-error)` 🎨
// - color: `var(--ui-color-on-error)` 🎨
const ToastError = "toast-error"

// @layer components
//
//
// **Visual:**
// - background: `var(--ui-color-secondary)` 🎨
// - color: `var(--ui-color-on-secondary)` 🎨
const ToastInfo = "toast-info"

// @layer components
//
//
// **Visual:**
// - background: `var(--ui-color-primary)` 🎨
// - color: `var(--ui-color-on-primary)` 🎨
const ToastSuccess = "toast-success"

// @layer components
//
//
// **Layout:**
// - cursor: `pointer`
// **Typography:**
// - font-size: `var(--ui-type-size-4xl)` 🎨
const TodoCheckboxLabel = "todo-checkbox-label"

// @layer components
//
//
// **Layout:**
// - margin: `0 auto`
// - max-width: `800px`
// - padding: `var(--ui-space-lg)` 🎨
const TodoContainer = "todo-container"

// @layer components
//
//
// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - gap: `var(--ui-space-md)` 🎨
// - width: `100%`
const TodoContent = "todo-content"

// @layer components
//
//
// **Visual:**
// - color: `var(--ui-color-primary)` 🎨
// **Layout:**
// - margin-bottom: `var(--ui-space-md)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
// - text-align: `center`
const TodoDescription = "todo-description"

// @layer components
//
//
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - flex-wrap: `wrap`
// - gap: `var(--ui-space-sm)` 🎨
// - justify-content: `space-between`
// - [+1 more layout properties]
const TodoFooter = "todo-footer"

// @layer components
//
//
// **Layout:**
// - display: `flex`
// - gap: `var(--ui-space-xs)` 🎨
const TodoFooterActions = "todo-footer-actions"

// @layer components
//
//
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const TodoFooterCount = "todo-footer-count"

// @layer components
//
//
// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - gap: `var(--ui-space-sm)` 🎨
const TodoHeader = "todo-header"

// @layer components
//
//
// **Layout:**
// - display: `flex`
// - justify-content: `center`
// **Typography:**
// - font-size: `var(--ui-type-size-xs)` 🎨
const TodoHelpText = "todo-help-text"

// @layer components
//
//
// **Layout:**
// - flex: `1`
// - width: `100%`
// **Typography:**
// - font-size: `var(--ui-type-size-lg)` 🎨
// - font-style: `italic`
const TodoInput = "todo-input"

// @layer components
//
//
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `var(--ui-space-sm)` 🎨
const TodoInputControls = "todo-input-controls"

// @layer components
//
//
// **Visual:**
// - background: `var(--ui-color-surface)` 🎨
// - border: `var(--ui-border-md) solid var(--ui-color-outline)` 🎨
// - border-radius: `var(--ui-radius-md)` 🎨
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `var(--ui-space-md)` 🎨
// - padding: `var(--ui-space-md)` 🎨
// **Effects:**
// - transition: `background var(--ui-duration-fast) var(--ui-ease-default)` 🎨
//
// **Interactions:**
// - `:hover`: Changes background to `var(--ui-color-surface-variant)`
const TodoItem = "todo-item"

// @layer components
//
//
// **Visual:**
// - opacity: `0.6`
const TodoItemCompleted = "todo-item-completed"

// @layer components
//
//
// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - gap: `var(--ui-space-sm)` 🎨
const TodoList = "todo-list"

// @layer components
//
//
// **Layout:**
// - max-height: `calc(100vh - 400px)`
// - overflow: `auto`
const TodoListContainer = "todo-list-container"

// @layer components
//
//
// **Typography:**
// - text-decoration: `line-through`
const TodoTaskCompleted = "todo-task-completed"

// @layer components
//
//
// **Layout:**
// - cursor: `pointer`
// - flex: `1`
// - user-select: `none`
// **Typography:**
// - font-size: `var(--ui-type-size-lg)` 🎨
const TodoTextLabel = "todo-text-label"

// @layer components
//
//
// **Visual:**
// - color: `var(--ui-color-primary)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-4xl)` 🎨
// - font-weight: `var(--ui-weight-bold)` 🎨
const TodoTitle = "todo-title"

// @layer components
//
//
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `var(--ui-space-sm)` 🎨
// - justify-content: `center`
const TodoTitleSection = "todo-title-section"

