// Code generated by cssgen. DO NOT EDIT.
//
// Component: Loading
// Generated: 2026-02-04 08:17:31

package ui

// Loading component styles
//
// For the full CSS class registry, see styles.gen.go

// @layer components
//
//
// **Layout:**
// - display: `inline-block`
const Loading = "loading"

// @layer components
//
//
// **Layout:**
// - align-items: `center`
// - content: `'...'`
// - display: `inline-block`
// - gap: `0.25rem`
// **Typography:**
// - font-weight: `bold`
// **Effects:**
// - animation: `loadingDots 1.5s infinite`
const LoadingDots = "loading-dots"

