// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Session struct {
	ID        string       `json:"id"`
	Data      string       `json:"data"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Todo struct {
	ID        string        `json:"id"`
	UserID    string        `json:"user_id"`
	Task      string        `json:"task"`
	Completed sql.NullInt64 `json:"completed"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}
