// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"
	"database/sql"
)

const countTodosByUser = `-- name: CountTodosByUser :one
SELECT COUNT(*) as count 
FROM todos 
WHERE user_id = ?
`

func (q *Queries) CountTodosByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodosByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTodo = `-- name: CreateTodo :exec
INSERT INTO todos (id, user_id, task, completed) 
VALUES (?, ?, ?, ?)
`

type CreateTodoParams struct {
	ID        string        `json:"id"`
	UserID    string        `json:"user_id"`
	Task      string        `json:"task"`
	Completed sql.NullInt64 `json:"completed"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) error {
	_, err := q.db.ExecContext(ctx, createTodo,
		arg.ID,
		arg.UserID,
		arg.Task,
		arg.Completed,
	)
	return err
}

const deleteAllTodosByUser = `-- name: DeleteAllTodosByUser :exec
DELETE FROM todos 
WHERE user_id = ?
`

func (q *Queries) DeleteAllTodosByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllTodosByUser, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos 
WHERE id = ?
`

func (q *Queries) DeleteTodo(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, data, created_at, updated_at FROM sessions WHERE id = ?
`

// Session queries
func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, user_id, task, completed, created_at, updated_at FROM todos 
WHERE id = ?
`

func (q *Queries) GetTodoByID(ctx context.Context, id string) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Task,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodosByUser = `-- name: GetTodosByUser :many
SELECT id, user_id, task, completed, created_at, updated_at FROM todos 
WHERE user_id = ? 
ORDER BY created_at DESC
`

func (q *Queries) GetTodosByUser(ctx context.Context, userID string) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodosByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Task,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleTodoCompleted = `-- name: ToggleTodoCompleted :exec
UPDATE todos 
SET completed = CASE WHEN completed = 0 THEN 1 ELSE 0 END, 
    updated_at = CURRENT_TIMESTAMP 
WHERE id = ?
`

func (q *Queries) ToggleTodoCompleted(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, toggleTodoCompleted, id)
	return err
}

const updateTodoTask = `-- name: UpdateTodoTask :exec
UPDATE todos 
SET task = ?, updated_at = CURRENT_TIMESTAMP 
WHERE id = ?
`

type UpdateTodoTaskParams struct {
	Task string `json:"task"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateTodoTask(ctx context.Context, arg UpdateTodoTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTodoTask, arg.Task, arg.ID)
	return err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (id, data, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
    data = excluded.data,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertSessionParams struct {
	ID   string `json:"id"`
	Data string `json:"data"`
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSession, arg.ID, arg.Data)
	return err
}
